import os
import pandas as pd

configfile: "config/config.yaml"

include: "rules/qc.smk"
include: "rules/alignment.smk"
include: "rules/reportQC.smk"
include: "rules/count.smk"
include: "rules/deg.smk"

# The 'all' rule defines the final targets of your pipeline
rule all:
   input:
       "results/multiqc/multiqc_report.html",
       "results/DEG/DEG_report.html"


