samples:
  - SRR15618886
  - SRR15618887
  - SRR15618888
  - SRR15618891
  - SRR15618892
  - SRR15618893
input_path: /opt/students/asma.malik/raw_data_exercise_20260218
samplesheet: config/samplesheet.tsv
genome_index: workflow/reference/mouse_index
gtf: workflow/reference/Mus_musculus.GRCm39.110.gtf